feat: Alterações em paciente e criação de get para planos de saúde
bugan/API-Voll.Med pull request #10
Opened 2023-02-15 21:35 UTC by Gabrielle-Ribeiro

Alterações feitas:
- Endereços são opcionais
- Http status adicionado
- Endereço só é retornado quando há consulta específica por id de paciente
- Validação de CPF
- Rota que informa os planos de saúde existentes

2023-02-16 12:54 UTC, bugan requested changes

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +    },
Essa lógica aqui existe pra que não tenha a senha sendo retornada. Funciona mas, do jeito que ta feito é muito frágil. em uma nova requisição pode ser que alguém esqueça de fazer essa validação e a senha seja retornada. provavelmente o TypeORm tem alguma anotation pra deixar isso registrado na Entidade e a senha não ser retornada

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +    },
achei isso aqui, vale testar https://www.kindacode.com/article/typeorm-2-ways-to-exclude-a-column-from-being-selected/

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +      cpf: true,
Outro problema desse jeito aqui é que todo campo novo vc teria que realmente mexer em todos os finds

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +  if (!validaCpf(cpf)) {
Aqui eu mudaria o nome da função pra `CPFValido` Só pq me parece mais natural na hora de ler/falar.

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
>  }
Toda essa parte de validação vc pode jogar pra outro arquivo e deixar isolado. Seu controller só importa essa função e usa ela

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteEntity.ts
> +  Nenhum,
Tava pensando que vale a pena usar "literals" aqui no enum e deixar como string o nome, assim no front fica mais fácil de consumir.

exemplo:
```
enum planoSaude{
amil ="AMIL",
nenhum = "NENHUM",
unimed = "UNIMED",
}
```
Assim, ao invés de retornar um número ele te devolve uma string

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteEntity.ts
> +  @Column('varchar', { length: 11 })
Ótimo que vc já deixou o tamanho do banco certo!

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +    if (paciente.endereco === null) {
Esse tipo de `if` é muito comum, mas tem uma estratégia que facilita na hora de organizar o código que é o "Early return"

Vale implementar pra ficar mais direto o entendimento do código
https://medium.com/swlh/return-early-pattern-3d18a41bba8

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +  if (allPacientes.length) {
faltou o `if(allPacientes.length == 0)`

2023-02-16 12:54 UTC, bugan commented on src/pacientes/pacienteController.ts
> +      paciente.planoSaude = planoSaude
Um construtor aqui ajudaria bastante

2023-02-16 19:59 UTC, Gabrielle-Ribeiro commented on src/pacientes/pacienteController.ts
> +      paciente.planoSaude = planoSaude
Adicionei um construtor no post, porém não sei se é possível usá-lo no update, pq a variável paciente é uma constante que a gente busca do banco, então não é possível alterar seu valor diretamente.

2023-03-02 11:57 UTC, bugan approved these changes

2023-03-02 11:57 UTC, bugan commented on src/pacientes/validacaoCPF.ts
> +export function CPFValido (cpf: string): boolean {
Provavelmente essa função vc consegue quebrar em funções menores. O comentário no meio do código tbm indica isso: `//Validação dos últimos dígitos` O problema de deixar ela inteira assim é que perdemos as regras que são aplicadas ao CPF. Eu não tenho um jeito fácil de tentar entender quais são essas regras sem precisar ler o código todo.

2023-03-02 11:57 UTC, bugan commented on src/planosDeSaude/planosDeSaudeController.ts
> +  nenhum: 'NENHUM',
Legal a separação Pra Literals :)

2023-03-02 11:57 UTC, bugan commented on src/pacientes/pacienteController.ts
> +      res.status(404).json('Paciente não encontrado!')
Depois de vc puxar o código da Camis que ta na mais vc pode colocar o erro personalizado que ela criou

2023-03-02 11:57 UTC, bugan commented on src/pacientes/pacienteRoutes.ts
> +  atualizarEnderecoPaciente,
Muito melhor com os nomes do contexto de negócio mesmo :)

2023-03-07 03:25 UTC, merged